### ISSUE TITLE
Statamic Version 5

### ISSUE THREAD

**Issue by johnwilsonuk** [stoffelio/statamic-turnstile#3]
The current version of Statamic Turnstile doesn't support the latest version of Statamic (v5). Is there a solution for this?

**Comment by stoffelio** [comment]
@johnwilsonuk - I have just tagged a new version, please let me know if there are any issues.

**Comment by stoffelio** [comment]
@wiegertschouten - thanks, now it's updated. Turns out packagist is very picky when it comes to release names.
