### ISSUE TITLE
Support other Turnstile options

### ISSUE THREAD

**Issue by andrewjmead** [stoffelio/statamic-turnstile#4]
Thanks for the package. It's working really well for me!

I would love to be able to customize [the turnstile options](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#configurations). Specifically, I'd like to be able to control the value of `data-theme` setting it to `light` rather than it's default value of `auto`.

Not sure if you had a good idea as to how this should be implemented. Maybe a `TURNSTILE_THEME` environment variable?

**Edit:** Actually, it would probably be more appropriate if the options are set when adding the turnstile field type to the form. This would allow every turnstile field to provide a different value for the options.

**Comment by andrewjmead** [comment]
Not bad! I can PR it if it's something you'd be open to including.

![Screenshot 2024-10-15](https://github.com/user-attachments/assets/9eeb7ba7-1964-4684-9965-a8f843a35506)

**Comment by andrewjmead** [comment]
Opened PR here https://github.com/stoffelio/statamic-turnstile/pull/5

**Comment by stoffelio** [comment]
I've merged your pr, thank you!
